# Generated by Django 5.0.3 on 2026-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_date_of_birth', models.DateField()),
                ('age_group', models.CharField(choices=[('u8', 'Under 8'), ('u10', 'Under 10'), ('u12', 'Under 12'), ('u14', 'Under 14'), ('u16', 'Under 16'), ('u18', 'Under 18')], max_length=10)),
                ('preferred_position', models.CharField(blank=True, max_length=50)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions we should know about')),
                ('previous_experience', models.TextField(blank=True, help_text='Previous football experience')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('interest_area', models.CharField(choices=[('playing', 'Playing for the Club'), ('volunteering', 'Volunteering'), ('sponsorship', 'Sponsorship'), ('partnership', 'Partnership'), ('youth', 'Youth Programs'), ('community', 'Community Programs')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='CoachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('goalkeeper_coach', 'Goalkeeper Coach'), ('fitness_coach', 'Fitness Coach'), ('physiotherapist', 'Physiotherapist'), ('analyst', 'Performance Analyst')], max_length=30)),
                ('team_type', models.CharField(choices=[('first', 'First Team'), ('women', "Women's Team"), ('junior', 'Junior Team'), ('academy', 'Academy')], default='first', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('bio', models.TextField(blank=True)),
                ('joined_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Coaching Staff',
                'ordering': ['role', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message_type', models.CharField(choices=[('general', 'General Inquiry'), ('membership', 'Membership Query'), ('tickets', 'Ticket Inquiry'), ('media', 'Media Request'), ('partnership', 'Partnership Opportunity'), ('complaint', 'Complaint')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('match', 'Match Photos'), ('training', 'Training'), ('event', 'Club Events'), ('stadium', 'Stadium'), ('fans', 'Fans'), ('historical', 'Historical')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('date_taken', models.DateField()),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube or video platform URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('match_date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('score', models.CharField(help_text='e.g., 3-1', max_length=20)),
                ('duration', models.CharField(help_text='e.g., 5:30', max_length=10)),
                ('views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('membership_type', models.CharField(choices=[('basic', 'Basic Membership'), ('premium', 'Premium Membership'), ('vip', 'VIP Membership'), ('season', 'Season Ticket')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='StadiumTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('tour_type', models.CharField(choices=[('standard', 'Standard Tour'), ('premium', 'Premium Tour'), ('vip', 'VIP Experience'), ('group', 'Group Tour')], max_length=20)),
                ('tour_date', models.DateField()),
                ('tour_time', models.TimeField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tour_date', '-tour_time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('team_type', models.CharField(choices=[('first', 'First Team'), ('women', "Women's Team"), ('junior', 'Junior Team'), ('academy', 'Academy')], default='first', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('bio', models.TextField(blank=True)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['jersey_number'],
                'unique_together': {('jersey_number', 'team_type')},
            },
        ),
    ]
